### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by victoriaponsiano** [worka/vanilla-js-wheel-zoom#32]
When attempting to run our tests that import the library throws an error in wheel-zoom.js.

```
Details:
     C:\Development\angular\node_modules\vanilla-js-wheel-zoom\src\wheel-zoom.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {
                                                                                      ^^^^^^
    SyntaxError: Cannot use import statement outside a module
      11 | import { Actions, EffectsModule } from '@ngrx/effects';
      12 | import { filter, take, takeUntil, tap, withLatestFrom } from 'rxjs';
    > 13 | import WZoom from 'vanilla-js-wheel-zoom';
         | ^
      14 | import { ofZoomDown } from './zoom-down-action-creator';
      15 | import { ofZoomUp } from './zoom-up-action-creator';
      16 |
      at Runtime.createScriptFromCode (../../../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../framework/src/lib/directives/zoom-and-pinch/zoom-and-pinch.directive.ts:13:1)
```

We think that a possible cause is because typings are missing. 
We have no problem doing a PR to fix it, but we're not sure what caused the error.

**Comment by worka** [comment]
Try use https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs for setup Jest

**Comment by worka** [comment]
Have you solved your problem?

**Comment by victoriaponsiano** [comment]
Yes, we solved it adding the library to the [transformIgnorePatterns](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) configuration option that Jest provides.
Thanks!
